server:
  port: 8090

spring:
  datasource:
    master:
      url: jdbc:mysql://47.114.94.33:3306/nacos?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: qingshi@123
#    driver-class-name:
    slave:
      url: jdbc:mysql://47.114.94.33:3306/nacos-config?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: qingshi@123
